UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_seitan_schnitzel_breaded_cutlet_plant_based_meat_alternative_israeli_comfort_food.jpg', image_verified = TRUE WHERE id = 'teva-1';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_tofu_natural_organic_plant_based_protein_block_israeli_made.png', image_verified = TRUE WHERE id = 'teva-2';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_seitan_kubeh_middle_eastern_specialty_plant_based_meat_alternative_israeli_cuisine.jpg', image_verified = TRUE WHERE id = 'teva-3';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_01_plant_based_meat_alternative_israeli_cuisine.jpg', image_verified = TRUE WHERE id = 'teva-4';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_21_burger_schnitzel_plant_based_deli.jpg', image_verified = TRUE WHERE id = 'teva-5';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_31_shawarma_kebab_middle_eastern_plant_based.jpg', image_verified = TRUE WHERE id = 'teva-6';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_11_seitan_tofu_based_protein_alternative.jpg', image_verified = TRUE WHERE id = 'teva-7';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_22_burger_schnitzel_plant_based_deli.jpg', image_verified = TRUE WHERE id = 'teva-8';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_15_seitan_tofu_based_protein_alternative.jpg', image_verified = TRUE WHERE id = 'teva-9';
UPDATE products SET image_path = '/images/vendors/teva-deli/teva_deli_vegan_specialty_product_26_burger_schnitzel_plant_based_deli.jpg', image_verified = TRUE WHERE id = 'teva-10';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Bulk Grains and Legumes Basket Display.jpg', image_verified = TRUE WHERE id = 'people-1';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Bulk Beans Oats Rice and Grains Basket Display.jpg', image_verified = TRUE WHERE id = 'people-2';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Bulk Flour and Powder Ingredients.jpg', image_verified = TRUE WHERE id = 'people-3';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Natural Herb Seasoning Mix Hebrew.jpg', image_verified = TRUE WHERE id = 'people-4';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Wan Ja Shan Tamari Soy Sauce Naturally Brewed.jpg', image_verified = TRUE WHERE id = 'people-5';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Pure Sesame Oil Taiwan.jpg', image_verified = TRUE WHERE id = 'people-6';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Organic Kosher Dill Pickles.jpg', image_verified = TRUE WHERE id = 'people-7';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Organic Spicy Sauerkraut.jpg', image_verified = TRUE WHERE id = 'people-8';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Fermented Hot Peppers.jpg', image_verified = TRUE WHERE id = 'people-9';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Fermented Okra with Live Culture.jpg', image_verified = TRUE WHERE id = 'people-10';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Spicy Kimchi Fermented.jpg', image_verified = TRUE WHERE id = 'people-11';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Organic Cucumber Relish.jpg', image_verified = TRUE WHERE id = 'people-12';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Organic Spicy Relish.jpg', image_verified = TRUE WHERE id = 'people-13';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Plain Non-Dairy Yogurt.jpg', image_verified = TRUE WHERE id = 'people-14';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Strawberry Non-Dairy Yogurt.jpg', image_verified = TRUE WHERE id = 'people-15';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Blueberry Non-Dairy Yogurt.jpg', image_verified = TRUE WHERE id = 'people-16';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Pineapple Non-Dairy Yogurt.jpg', image_verified = TRUE WHERE id = 'people-17';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Quintessence Sweet and Sour Ginger 3-Pack.jpg', image_verified = TRUE WHERE id = 'people-18';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Great Northern Organic Maple Syrup.jpg', image_verified = TRUE WHERE id = 'people-19';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - FOCO Coconut Water Variety Pack.jpg', image_verified = TRUE WHERE id = 'people-20';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Laverland Crunch Sea Salt Seaweed Snack 9-Pack.jpg', image_verified = TRUE WHERE id = 'people-21';
UPDATE products SET image_path = '/images/vendors/people-store/Peoples Store - Laverland Crunch Wasabi Seaweed Snack 9-Pack.jpg', image_verified = TRUE WHERE id = 'people-22';
UPDATE products SET image_path = '/images/vendors/garden-of-light/1.jpg', image_verified = TRUE WHERE id = 'garden-1';
UPDATE products SET image_path = '/images/vendors/garden-of-light/2.jpg', image_verified = TRUE WHERE id = 'garden-2';
UPDATE products SET image_path = '/images/vendors/garden-of-light/3.jpg', image_verified = TRUE WHERE id = 'garden-3';
UPDATE products SET image_path = '/images/vendors/garden-of-light/4.jpg', image_verified = TRUE WHERE id = 'garden-4';
UPDATE products SET image_path = '/images/vendors/garden-of-light/5.jpg', image_verified = TRUE WHERE id = 'garden-5';
UPDATE products SET image_path = '/images/vendors/garden-of-light/6.jpg', image_verified = TRUE WHERE id = 'garden-6';
UPDATE products SET image_path = '/images/vendors/garden-of-light/7.jpg', image_verified = TRUE WHERE id = 'garden-7';
UPDATE products SET image_path = '/images/vendors/garden-of-light/8.jpg', image_verified = TRUE WHERE id = 'garden-8';
UPDATE products SET image_path = '/images/vendors/garden-of-light/9.jpg', image_verified = TRUE WHERE id = 'garden-9';
UPDATE products SET image_path = '/images/vendors/garden-of-light/10.jpg', image_verified = TRUE WHERE id = 'garden-10';
UPDATE products SET image_path = '/images/vendors/garden-of-light/11.jpg', image_verified = TRUE WHERE id = 'garden-11';
UPDATE products SET image_path = '/images/vendors/garden-of-light/12.jpg', image_verified = TRUE WHERE id = 'garden-12';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meat_grilled_seitan_steaks_plant_based_protein_alternative.jpg', image_verified = TRUE WHERE id = 'queens-1';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meatballs_pasta_dish_plant_based_italian_cuisine_tomato_sauce.jpg', image_verified = TRUE WHERE id = 'queens-2';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_middle_eastern_shawarma_pita_wrap_plant_based_meat_alternative.jpg', image_verified = TRUE WHERE id = 'queens-3';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_burger_seitan_patty_sesame_bun_tomato_lettuce_plant_based_sandwich.jpg', image_verified = TRUE WHERE id = 'queens-4';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meat_kabab_skewer_dish_plant_based_middle_eastern_cuisine.jpg', image_verified = TRUE WHERE id = 'queens-5';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_seitan_cutlets_breaded_crispy_herb_dip_arugula_salad_cherry_tomatoes.jpg', image_verified = TRUE WHERE id = 'queens-6';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meat_seitan_sandwich_plant_based_deli_style_bread_filling.jpg', image_verified = TRUE WHERE id = 'queens-7';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meat_seitan_kebabs_grilled_skewers_plant_based_barbecue_alternative.jpg', image_verified = TRUE WHERE id = 'queens-8';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_seitan_strips_teriyaki_sauce_sesame_seeds_scallions_asian_style.jpg', image_verified = TRUE WHERE id = 'queens-9';
UPDATE products SET image_path = '/images/vendors/queens-cuisine/queens_cuisine_vegan_meatballs_cooking_pot_plant_based_protein_homestyle_preparation.png', image_verified = TRUE WHERE id = 'queens-10';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_ice_cream_chocolate_tahini_swirl_cup_with_cacao_nibs.jpeg', image_verified = TRUE WHERE id = 'gahn-1';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_sorbet_lime_coconut_fresh_garnish_bowl.jpg', image_verified = TRUE WHERE id = 'gahn-2';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_ice_cream_passion_mango_double_scoop_cup.jpg', image_verified = TRUE WHERE id = 'gahn-3';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_sundae_date_caramel_vanilla_walnut_toppings_glass.jpeg', image_verified = TRUE WHERE id = 'gahn-4';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_parfait_chocolate_almond_caramel_layered_glass.jpg', image_verified = TRUE WHERE id = 'gahn-5';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_popsicle_berry_hibiscus_frozen_bar_wooden_stick.jpeg', image_verified = TRUE WHERE id = 'gahn-6';
UPDATE products SET image_path = '/images/vendors/gahn-delight/gahn_delight_ice_cream_pistachio_rose_triple_scoop_ceramic_bowl.jpeg', image_verified = TRUE WHERE id = 'gahn-7';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_community_apparel_product_01_wellness_lifestyle_village_of_peace_heritage_clothing.jpg', image_verified = TRUE WHERE id = 'vop-1';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_community_apparel_product_02_wellness_lifestyle_village_of_peace_heritage_clothing.jpg', image_verified = TRUE WHERE id = 'vop-2';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_community_apparel_product_03_wellness_lifestyle_village_of_peace_heritage_clothing.jpg', image_verified = TRUE WHERE id = 'vop-3';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_community_apparel_product_04_wellness_lifestyle_village_of_peace_heritage_clothing.jpg', image_verified = TRUE WHERE id = 'vop-4';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_community_apparel_product_05_wellness_lifestyle_village_of_peace_heritage_clothing.jpg', image_verified = TRUE WHERE id = 'vop-5';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_heritage_home_decor_product_06_50_year_celebration_cultural_art_community_pride.jpg', image_verified = TRUE WHERE id = 'vop-6';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_heritage_home_decor_product_07_50_year_celebration_cultural_art_community_pride.jpg', image_verified = TRUE WHERE id = 'vop-7';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_heritage_home_decor_product_08_50_year_celebration_cultural_art_community_pride.jpg', image_verified = TRUE WHERE id = 'vop-8';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_heritage_home_decor_product_09_50_year_celebration_cultural_art_community_pride.jpg', image_verified = TRUE WHERE id = 'vop-9';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_heritage_home_decor_product_10_50_year_celebration_cultural_art_community_pride.jpg', image_verified = TRUE WHERE id = 'vop-10';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_wellness_education_product_11_healing_books_holistic_health_community_wisdom.jpg', image_verified = TRUE WHERE id = 'vop-11';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_wellness_education_product_12_healing_books_holistic_health_community_wisdom.jpg', image_verified = TRUE WHERE id = 'vop-12';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_wellness_education_product_13_healing_books_holistic_health_community_wisdom.jpg', image_verified = TRUE WHERE id = 'vop-13';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_wellness_education_product_14_healing_books_holistic_health_community_wisdom.jpg', image_verified = TRUE WHERE id = 'vop-14';
UPDATE products SET image_path = '/images/vendors/vop-shop/vop_shop_wellness_education_product_15_healing_books_holistic_health_community_wisdom.jpg', image_verified = TRUE WHERE id = 'vop-15';